---
name: Build and Publish PDF

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build_latex:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build PDF
        uses: xu-cheng/latex-action@v4
        with:
          root_file: cv-gboeing.tex

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::800820568312:role/github-actions-gboeing-cv
          aws-region: us-west-2

      - name: Upload PDF to AWS s3
        run: aws s3 cp ./cv-gboeing.pdf s3://cv-gboeing/
