---
name: Build and Publish PDF

on:  # yamllint disable-line rule:truthy
  push:
    branches: [main, s3]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::800820568312:role/github-actions-gboeing-cv
          role-session-name: github-actions-gboeing-cv
          aws-region: us-west-2

      - name: Build PDF
        uses: xu-cheng/latex-action@v3
        with:
          root_file: cv-gboeing.tex

      - name: Upload PDF to S3
        run: aws s3 cp ./cv-gboeing.pdf s3://cv-gboeing/
